### ISSUE TITLE
Разработка стратегии сравнения изображений.

### ISSUE THREAD

**Issue by ghost** [Weiaett/CruelAlarm#12]
Экспериментально установить наилучший способ выявления features в изображении и их сравнения.

**Comment by alexpdk** [comment]
Эксперименты показали, что алгоритм ORB определяет ключевые точки на изображениях кучно, отдавая предпочтение бликам света, а не значимым деталям. Для повышения уникальности набора дескрипторов был использован алгоритм выделения контуров MSER, позволяющий обнаружить на фотографии выделяющиеся по цвету области. Для каждй области с помощью ORB подсчитываются дескрипторы, которые используются при сравнении изображений.
Кроме того, для повышения надёжности подхода добавлено сравнение фотографий по пикселям в эвклидовой метрике. Смещение фотографий относительно друг друга вычисляется итерационным методом на основе среднего смещения в списке парных областей, полученном в ходе работы MSER/ORB. 
Приложение, производящее сравнение фотографий описанным способом, залито в ветку comparison проекта.
