### ISSUE TITLE
Эвристика принятия решения модулем сравнения.

### ISSUE THREAD

**Issue by ghost** [Weiaett/CruelAlarm#13]
Экспериментально установить эвристику, по которой модуль сравнения устанавливает идентичность изображений на основе результатом работы модуля.

**Comment by alexpdk** [comment]
Была разработан эвристический алгоритм для сравнения снимков, сделанных пользователем приложения. Алгоритм выявляет ключевые точки на изображениях и определяет сдвиг изображений относительно друг друга, при котором достигается лучшее соответствие между выбранными точками. Затем производится попиксельное сравнение изображений с учётом сдвига для определения соответствия объектов в кадре. Сделанные пользователем снимки перед началом работы сжимаются для ускорения приложения и уменьшения объёма выделяемой памяти.

Сервис, отвечающий за выполение алгоритма, интегрирован с менеджером фотографий для получения снимков с камеры. Приложение, позволяющее сравнивать снимки на основе разработанной эвристики, залито в ветку comparison проекта.
