### ISSUE TITLE
Макет приложения.

### ISSUE THREAD

**Issue by ghost** [Weiaett/CruelAlarm#2]
# Задача

Разработать макет приложения, включающий все основные экраны и диалоги. Выбрать цветовую схему и тему оформления.
### Экран загрузки (splash screen)

Содержит логотип. Исчезает при клике по экрану, или через 2 секунды после появления.
### Экран списка будильников

Содержит панель инструментов (toolbar), список карточек будильников и кнопку добавления будильника (floating button).
1. Панель инструментов содержит название экрана, кнопку перехода к настройкам, флажок для выделения (или снятия выделения) всех будильников (checkbox). Если выделен хотя бы один будильник, на панели инструментов изменяется название экрана, а также кнопка перехода к настройкам заменяется кнопкой удаления выделенных будильников.
2. Карточка будильника имеет 3 состояния: свернутое, развернутое и выделенное. Изначально все карточки свернуты. Единовременно развернутой может быть только одна карточка. Карточка разворачивается по клику. Содержание свернутой карточки: время будильника, состояние включен или выключен (toggle button), строка с перечислением дней активности будильника (сегодня/завтра/дни недели), шеврон, подсказывающий пользователю, что карточку можно развернуть. В развернутом состоянии добавляются: выбор дней активности будильника (один раз или определенные дни недели), выбор мелодии, редактирование описания, выбор фотографий. При долгом клике по одной карточке на всех карточках появляется флажок для выделения (или снятия выделения).
### Экран настроек

Содержит панель инструментов (toolbar), список настроек, подвал (footer).
1. Панель инструментов содержит название экрана и кнопку “Назад”.
2. Список настроек: выбор общей мелодии, вибросигнал (вкл/выкл), интервал повтора (1 – 30 минут), автовыключение (15 минут – 6 часов или никогда), кнопка перехода к менеджеру фотографий.
3. Подвал содержит кнопку перехода на экран с информацией о приложении.
### Менеджер фотографий

Менеджер фотографий позволяет просматривать, добавлять и удалять фотографии. Содержит панель инструментов, сетку с миниатюрами фотографий и кнопку добавления фотографии (floating button).
1. Панель инструментов содержит название экрана, флажок для выделения (или снятия выделения) всех фотографий (checkbox). Если выделена хотя бы одна фотография, на панели инструментов изменяется название экрана, а также появляется кнопка удаления выделенных фотографий.
2. При долгом клике по одной миниатюре фотографии на всех миниатюрах появляется флажок для выделения (или снятия выделения) фотографии. При простом клике по миниатюре фотография открывается на полный экран.
3. При нажатии на кнопку добавления фотографии открывается камера. Сделанная фотография проходит проверку на корректность (недопустима, например, полностью черная фотография). Если фотография корректна, происходит сохранение, иначе выводится сообщение о некорректности фотографии.
## Сценарий выключения активного будильника
- В настроенное время начинает воспроизводиться выбранная мелодия, и на экране смартфона показывается одна из выбранных фотографий.
- Поверх фотографии выведено описание будильника. При клике на описание, фотография исчезает, и открывается камера.
- На экране камеры присутствует иконка с фотографией. Пока пользователь держит палец на иконке, на экране появляется полупрозрачная фотография, которую пользователь должен воспроизвести.
- Когда пользователь делает фотографию, если она совпадает с требуемой, будильник отключается, иначе выводится сообщение о неверной фотографии. В случае неудачи, если в настройках будильника выбрано несколько фотографий, на экране появляется кнопка “Другая фотография”, меняющая требующуюся фотографию.
- Если в течение пяти минут пользователь не справляется с заданием, появляется кнопка “Сдаться”. При нажатии на нее, на экран выводится математический пример, который пользователю необходимо решить. В случае успешного решения, будильник отключается.

**Comment by gboydf** [comment]
Экраны приложения
[https://drive.google.com/file/d/0B91gqtdIq-Teci1xazFTLVdpeFE/view?usp=sharing](url)

**Comment by alexeygasenko** [comment]
https://bitbucket.org/gboydf/cruel-alarm/overview
