### ISSUE TITLE
Средства сравнения изображений.

### ISSUE THREAD

**Issue by ghost** [Weiaett/CruelAlarm#3]
Изучить предметную область, определить набор технологий для обработки и сравнения изображений для платформы Android.

**Comment by alexpdk** [comment]
Для реализации сравнения изображений на платформе Android была выбрана свободно распространяемая библиотека алгоритмов машинного зрения OpenCV. Данная библиотека написана на C++, однако разработчик предоставляет обёртки для популярных языков и платформ, включая версию для Android разработки.

Для сравнения изображений OpenCV предоставляет пакет featrures2d, включающий в себя следующие методы: определение углов методом Shi-Tomasi, FAST/BRIEF, SIFT, SURF, ORB. Основные особенности алгоритмов:
- Метод Shi-Tomasi способен сравнивать повёрнутые изображения, но некорректно работает при изменении масштаба
- FAST/BRIEF, напротив, не способен сравнивать повёрнутые изображения, т.к. не умеет вычислять градиент в опроных точках
- SIFT и SURF(ускоренный SIFT) считаются наиболее передовыми алгоритмами. Однако они являются проприетарными и в новых версиях OpenCV вынесены в отдельный пакет, при использовании которого возникнут проблемы с размещением приложения на PlayMarket.
- ORB - непроприетарная модификация FAST/BRIEF, позволяющая сравнивать повёрнутые изображения. Использование ORB даёт менее точные результаты, чем SIFT/SURF, однако он достаточно быстр и удобен в применении.

Было решено исользовать в разрабатываемом приложении алгоритм ORB, дополняя при необходимости методами работы с цветами/контурами.
