### ISSUE TITLE
Модуль загрузки изображений средствами OpenCV.

### ISSUE THREAD

**Issue by ghost** [Weiaett/CruelAlarm#5]
Реализовать загрузку изображений, преобразование их в необходимое представление, отображение на экране.

**Comment by alexpdk** [comment]
Были реализованы следующие возможности:
- Загрузка изображений из формата android.graphics.bitmap
- Преобразование изображений в необходимое OpenCV матричное представление
- Преобразование 4-канальных изображений в 3-канальные для получения возможности изменять их средствами OpenCV
- Отрисовка поверх изображений сетки сопоставления для последующей отладки стратегий сравнения изображений
- Экспорт изображений в формате android.graphics.bitmap для вывода на экран

Тестовое приложение, использующее разработанный модуль, залито в ветку comparison проекта.
